# Generated by Django 5.0.3 on 2024-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("imei", models.CharField(max_length=200)),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Bought", "Bought"),
                            ("In Transit", "In Transit"),
                            ("In Progress", "In Progress"),
                            ("Pending Sale", "Pending Sale"),
                            ("Sold", "Sold"),
                            ("Error", "Error"),
                        ],
                        default="Bought",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
