# Generated by Django 5.0.3 on 2024-03-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="imei",
            field=models.CharField(max_length=200, unique=True, verbose_name="IMEI"),
        ),
    ]
