# Generated by Django 5.0.3 on 2024-03-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0002_alter_phone_imei"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="phones.phone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Part",
                "verbose_name_plural": "Phone Parts",
            },
        ),
    ]
