# Generated by Django 5.0.3 on 2024-03-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0003_phonepart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonepart",
            name="phone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="phones.phone",
            ),
        ),
    ]
