# Generated by Django 5.0.3 on 2024-04-13 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0004_alter_phonepart_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phone",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="phonepart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phonepart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
