version: "3.9"

name: "accounting-admin"

services:
  db:
    image: postgres:16.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
